### ISSUE TITLE
Specify node version that this repo works with

### ISSUE THREAD

**Issue by andreiashu** [OpenZeppelin/damn-vulnerable-defi#1]
Running the tests in node v14 throws errors in before/after hooks: `Error: Callback was already called.`

Might be worth:

* updating the Readme to explain which node versions are supported
* adding an [engines](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines) specification in package.json

Let me know your thoughts. I can send a PR but just wanted to get your thoughts first.

PS: thanks for this great work
Edit: forgot to mention, but everything works as expected with `v12.11.1`

**Comment by vdg0** [comment]
Weird... 
I got errors with node v12.11.1 but everything fine in a fresh manjaro, with base-devel, python2.7 and node: v12.20.1 (npm v6.14.11).

**Comment by andreiashu** [comment]
@vdg0 what kind of errors are you getting?
on v12 I only get warnings about the license identifier but no errors.

**Comment by vdg0** [comment]
I don't remember specifics anymore and don't catch that log.
But, in v12.11.1 was some trouble with dependencies compilation. But, 0 errors with v12.20.1 lts/erbium.

**Comment by abcoathup** [comment]
Hi @andreiashu!  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by tinchoabbate** [comment]
Thanks @andreiashu for reporting! I'll take a closer look during the weekend, I never had a problems with node's version during testing, but it might be the case some dependencies don't work with specific versions. I'll come back here once I have it clearer.

**Comment by tinchoabbate** [comment]
I have been able to install all dependencies and run all challenges with version `12.20.0` of node.  have added a "Troubleshooting" section to the README specifying this.

Thanks for reporting @andreiashu and @vdg0
