### ISSUE TITLE
New success condition Puppet Challenge

### ISSUE THREAD

**Issue by Koowah** [OpenZeppelin/damn-vulnerable-defi#14]
Hi (@tinchoabbate ),

Apologies if I'm not supposed to post here; there is no issue tab on the author's V3.

In `puppet V3`, the player is supposed to succeed `executing only a single transaction`. I don't think this is possible. Even if one was to deploy a contract to handle all necessary steps, that's still contract deployment + contract call (+ token approval to attack contract).

Am I missing something here or is it a mistake ?
Thank you for your help,
Cheers 😄

**Comment by tinchoabbate** [comment]
Hey @Koowah. Thanks for the notice. I opened discussions tab in https://github.com/tinchoabbate/damn-vulnerable-defi/discussions

Not sure what you're referring to regarding the success condition in Puppet v3. It does not say nor enforce that you should pass the challenge in a single transaction.

**Comment by Koowah** [comment]
I don't know where that "V3" came from 😄 It's actually in the [first puppet challenge](https://github.com/tinchoabbate/damn-vulnerable-defi/blob/master/test/puppet/puppet.challenge.js).

**Comment by tinchoabbate** [comment]
You might be missing something :) Have you checked the new feature of the Damn Valuable Token ?
Anyway, please let's keep any future question or similar here: https://github.com/tinchoabbate/damn-vulnerable-defi/discussions
Thanks!

**Comment by Koowah** [comment]
Oh flash swaps right! Thanks for your answers.
See you in your repo 😄
