### ISSUE TITLE
Should be upgraded to use official hardhat

### ISSUE THREAD

**Issue by Bereket-G** [OpenZeppelin/damn-vulnerable-defi#9]
### npm install error on Apple Silcon m1 chip

6828 verbose stack Error: exited with error code: null
6828 verbose stack     at ChildProcess.<anonymous> (/Users/bereket/.nvm/versions/node/v12.22.9/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
6828 verbose stack     at ChildProcess.emit (events.js:314:20)
6828 verbose stack     at maybeClose (internal/child_process.js:1022:16)
6828 verbose stack     at Socket.<anonymous> (internal/child_process.js:444:11)
6828 verbose stack     at Socket.emit (events.js:314:20)
6828 verbose stack     at Pipe.<anonymous> (net.js:675:12)
6829 verbose cwd /Volumes/secondary_drive/blockChain-learning/damn-vulnerable-defi
6830 verbose Darwin 21.0.1
6831 verbose argv "/Users/bereket/.nvm/versions/node/v12.22.9/bin/node" "/Users/bereket/.nvm/versions/node/v12.22.9/bin/npm" "i" "--verbose"
6832 verbose node v12.22.9
6833 verbose npm  v6.14.15
6834 error Error while executing:
6834 error /usr/bin/git ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
6834 error
6834 error rosetta error: /var/db/oah/279281322164224_279281322164224/ea50d481d6c5a2b4c424ed9865d6cb39b67491f7198ae2d9ee0ae1d0efe8aa26/libxcrun.dylib.aot: attachment of code signature supplement failed: 1
6834 error

**Comment by tinchoabbate** [comment]
Hey @Bereket-G , please refer to the most up-to-date version of Damn Vulnerable DeFi at https://github.com/tinchoabbate/damn-vulnerable-defi. Thanks!

**Comment by Bereket-G** [comment]
Ahha, okay cool thanks. @tinchoabbate
